apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: tax-calculator-pipeline
spec:
  workspaces:
    - name: shared-workspace
  tasks:
    - name: install-dependencies
      taskRef:
        name: npminstall
      workspaces:
        - name: workspace
          workspace: shared-workspace

    - name: run-tests
      taskRef:
        name: jasmine
      runAfter:
        - install-dependencies
      workspaces:
        - name: workspace
          workspace: shared-workspace

    - name: build-docker-image
      taskRef:
        name: buildah
      runAfter:
        - run-tests
      workspaces:
        - name: workspace
          workspace: shared-workspace
      params:
        - name: IMAGE
          value: us.icr.io/my-namespace/tax-calculator:latest
